### ISSUE TITLE
Issues with latest Raspbian Lite (2019-04-08)

### ISSUE THREAD

**Issue by patrickjuchli** [RevolutionPi/imagebakery#7] opened 2019-04-18 14:10 UTC
Baking an image with the latest Raspbian Lite (2019-04-08-raspbian-stretch-lite.zip) and flashing a device with it leads to the following error message after entering product/serial/mac on first-run:

```
/usr/sbin/revpi-factory-reset: line 49: /usr/bin/dtoverlay: No such file or directory
Password:	getSerNum() failed -1
```

Adjusting the README to mention a specific version of Raspbian instead of the latest one would already be helpful enough.

**Comment by l1k** [comment] 2020-03-16 14:40
My apologies for the delay. This issue is most likely caused by a bug in the libfdisk1 package which we've fixed in October 2019. See this <a href="https://revolution.kunbus.de/forum/viewtopic.php?f=6&t=1859&p=7029#p7029">forum post</a> for details. Thanks for the suggestion to identify the currently supported Raspbian image, I've amended the README accordingly with commit 87907cb1203c. Does this suit your needs?

**Closed** 2020-08-13 11:55 UTC
